name: CI
on:
    pull_request:
        branches:
            - main
    push:
        paths:
            - packages/**
            - rollup.config.js
            - package.json
            - pnpm-lock.yaml
            - .github/workflows/**
    workflow_dispatch:

jobs:
    build:
        name: Build
        # do not run if commit message contains [skip ci] or is a release
        if: "!contains(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '(main) release: ')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v3

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - run: pnpm install --frozen-lockfile
            - run: pnpm build
              env:
                  GITHUB_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
                  GITLAB_CLIENT_ID: ${{ secrets.GITLAB_CLIENT_ID }}
                  CODEBERG_CLIENT_ID: ${{ secrets.CODEBERG_CLIENT_ID }}
                  AI_API_URL: ${{ secrets.AI_API_URL }}
                  AI_API_PASSWORD: ${{ secrets.AI_API_PASSWORD }}
            - name: log dist size
              run: |
                  echo $(du -sh dist | cut -f1)
    lint:
        name: Lint
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v3

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - run: pnpm install --frozen-lockfile
            - run: pnpm lint
            - run: pnpm lint:styles
