name: Release
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        name: Release
        if: "startsWith(github.event.head_commit.message, '(main) release: ') || github.event_name == 'workflow_dispatch'"
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v3

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Get package.json version
              id: package
              run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

            - name: Create Sentry release
              uses: getsentry/action-release@v1
              if: ${{ matrix.os == 'ubuntu-latest' }}
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
              with:
                  environment: production
                  version: ${{ steps.package.outputs.version }}

            - run: |
                  node -v
                  npm -v
                  pnpm -v

            - run: pnpm i --frozen-lockfile
              name: Install

            - run: pnpm build
              name: Build
              env:
                  GITHUB_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
                  GITLAB_CLIENT_ID: ${{ secrets.GITLAB_CLIENT_ID }}
                  CODEBERG_CLIENT_ID: ${{ secrets.CODEBERG_CLIENT_ID }}
                  AI_API_URL: ${{ secrets.AI_API_URL }}
                  AI_API_PASSWORD: ${{ secrets.AI_API_PASSWORD }}

            - run: pnpm make:${{ matrix.os }} --publish always
              name: Make
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
